### ISSUE TITLE
Can you help me? 

### ISSUE THREAD

**Issue by byoxygen** [hbenormous/haxball-headless-help#3]
Hello bro! 

I want to make offside in haxball like this: https://imgur.com/a/f2JN1Uh

How can I do it?

**Comment by guguxh** [comment]
Bro, this is a thing really complicated to make because need a lot of math to get position of players in all ticks; to see if a player is in offside and a function to make this u see in the printscreen.

**Comment by byoxygen** [comment]
> Bro, this is a thing really complicated to make because need a lot of math to get position of players in all ticks; to see if a player is in offside and a function to make this u see in the printscreen.

When a player is in control of the ball and attempting to pass it forward an offside offence may occur.

**Comment by hbenormous** [comment]
> Olá mano!
> 
> Eu quero fazer o impedimento no haxball assim: https://imgur.com/a/f2JN1Uh
> 
> Como eu posso fazer isso?

[ PT-BR ]
> Você vai identificar a posição da bola:
https://github.com/haxball/haxball-issues/wiki/Headless-Host#getballposition

> Determinar a posição do jogador:
https://github.com/haxball/haxball-issues/wiki/Headless-Host#ongametick

**Você pode pegar alguns exemplos no issues do hh host:**
https://github.com/haxball/haxball-issues/issues

**Comment by byoxygen** [comment]
> > Olá mano!
> > Eu quero fazer o impedimento no haxball assim: https://imgur.com/a/f2JN1Uh
> > Como eu posso fazer isso?
> 
> [ PT-BR ]
> 
> > Você vai identificar a posição da bola:
> > https://github.com/haxball/haxball-issues/wiki/Headless-Host#getballposition
> 
> > Determinar a posição do jogador:
> > https://github.com/haxball/haxball-issues/wiki/Headless-Host#ongametick
> 
> **Você pode pegar alguns exemplos no issues do hh host:** https://github.com/haxball/haxball-issues/issues

I already know all of them but very much possibility is there.

**Comment by hbenormous** [comment]
> > > Olá mano!
> > > Eu quero fazer o impedimento no haxball assim: https://imgur.com/a/f2JN1Uh
> > > Como eu posso fazer isso?
> > 
> > 
> > [ PT-BR ]
> > > Você vai identificar a posição da bola:
> > > https://github.com/haxball/haxball-issues/wiki/Headless-Host#getballposition
> > 
> > 
> > > Determinar a posição do jogador:
> > > https://github.com/haxball/haxball-issues/wiki/Headless-Host#ongametick
> > 
> > 
> > **Você pode pegar alguns exemplos no issues do hh host:** https://github.com/haxball/haxball-issues/issues
> 
> I already know all of them but very much possibility is there.

https://hbanz.org/realsoccer/

**Comment by byoxygen** [comment]
> > > > Olá mano!
> > > > Eu quero fazer o impedimento no haxball assim: https://imgur.com/a/f2JN1Uh
> > > > Como eu posso fazer isso?
> > > 
> > > 
> > > [ PT-BR ]
> > > > Você vai identificar a posição da bola:
> > > > https://github.com/haxball/haxball-issues/wiki/Headless-Host#getballposition
> > > 
> > > 
> > > > Determinar a posição do jogador:
> > > > https://github.com/haxball/haxball-issues/wiki/Headless-Host#ongametick
> > > 
> > > 
> > > **Você pode pegar alguns exemplos no issues do hh host:** https://github.com/haxball/haxball-issues/issues
> > 
> > 
> > I already know all of them but very much possibility is there.
> 
> https://hbanz.org/realsoccer/

Not supporting offside. I have checked a few months ago.

You can look mate.

**Comment by byoxygen** [comment]
> > > > Olá mano!
> > > > Eu quero fazer o impedimento no haxball assim: https://imgur.com/a/f2JN1Uh
> > > > Como eu posso fazer isso?
> > > 
> > > 
> > > [ PT-BR ]
> > > > Você vai identificar a posição da bola:
> > > > https://github.com/haxball/haxball-issues/wiki/Headless-Host#getballposition
> > > 
> > > 
> > > > Determinar a posição do jogador:
> > > > https://github.com/haxball/haxball-issues/wiki/Headless-Host#ongametick
> > > 
> > > 
> > > **Você pode pegar alguns exemplos no issues do hh host:** https://github.com/haxball/haxball-issues/issues
> > 
> > 
> > I already know all of them but very much possibility is there.
> 
> https://hbanz.org/realsoccer/

Not supporting offside. I have checked a few months ago.

**Comment by byoxygen** [comment]
@Skarmunds

**Comment by byoxygen** [comment]
Who knows that?

**Comment by hbenormous** [comment]
> Who knows that?

Entre no discord > https://discord.gg/UWYuxwEKfn

Tem uma pessoa que tem um script de real soccer exatamente como você quer

**Comment by byoxygen** [comment]
Has not been solved yet.
